name: CI

on:
  push:
    branches: [ main, ci-testing ]
  pull_request:
    branches: [ main, ci-testing ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dosemate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run ESLint
      run: npm run lint
    
    - name: TypeScript type check
      run: npx tsc --noEmit
    
    - name: Run Format Check
      run: npm run prettier